server:
  port: 8080 
  
spring:
  application:
    name: configclient
  cloud:
    consul:
      host: 172.21.101.85
      port: 8500
      discovery:
      #是否启用服务发现
        enabled: true
        service-name: ${spring.application.name}
        #配置健康检查路径
        health-check-path: /health
        #配置健康检查时间间隔
        health-check-interval: 15s
        #配置实例id  myconsul${random.uuid}
        instance-id: ${spring.application.name}:${random.uuid}
        #配置服务注册
        register: true
        #服务停止时取消注册，http://www.imooc.com/article/286883?block_id=tuijian_wz
        deregister: true
        #表示注册时使用ip而不是hostname
        prefer-ip-address: true
        #健康检查失败多长时间取消注册
        health-check-critical-timeout: 30s  

  datasource:
    driver-class-name: com.microsoft.sqlserver.jdbc.SQLServerDriver
    url: jdbc:sqlserver://168.111.18.188;Databasename=dincan
    username: sa
    password: cs089708980899
   
